# eo_data_pipeline/config/hydra_config.yaml
defaults:
  - _self_

earth_search:
  url: "https://earth-search.aws.element84.com/v1"

pipeline:
  time_steps: 
    start: "2023-01-01"
    end: "2023-02-25"
  aoi: [13.822174072265625, 45.85080395917834, 14.55963134765625, 46.29191774991382]
  spectral_bands: [ "blue", "nir"]  # RGB + NIR

storage:
  type: "local"
  path: "./data/raw/"
  catalog_path: "./data/catalog_metadata/"

