name: run unit tests

on:
  push:
    branches:
      - main

jobs:
  build:

    name: build_eo_data_pipeline
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
    
    - name: install dependencies
      run: |
        apt-get update && apt-get install -y build-essential libssl-dev libffi-dev python3-dev
        pip install poetry==1.8.3
        poetry install --with dev

    
    - name: run unit tests
      run: |
        source $(poetry env info --path)/bin/activate
        make test
